---
name: IO-YAML
version: 0.08
author:
  - Paul Hoffman (nkuitse AT cpan DOT org)
abstract: read and write YAML streams incrementally
license: unknown
requires:
  Errno: 0
  Fcntl: 0
  File::Copy: 0
  IO::File: 0
  IO::Scalar: 0
  Symbol: 0
  YAML: 0
provides:
  IO::YAML:
    file: lib/IO/YAML.pm
    version: 0.08
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
