#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-YAML
version:      0.06
version_from: lib/IO/YAML.pm
installdirs:  site
requires:
    Fcntl:                         0
    File::Copy:                    0
    Errno:                         0
    YAML:                          0
    IO::Scalar:                    0
    Symbol:                        0
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
